CREATE TABLE USER_INFO (
    UNIQ_ID AUTO_INCRIMENT,
    EMAIL VARCHAR(40),
    User_PASSWORD VARCHAR(120),
    DATECREATED DATETIME NOT NULL DEFAULT(GETDATE())
);

CREATE TABLE SCAN_T (
  SCAN_ID INT AUTO_INCRIMENT,
  DATECREATED DATETIME NOT NULL DEFAULT(GETDATE()),
  PRIMARY KEY (SCAN_ID),
  FOREIGN KEY REFERENCES USER_INFO(UNIQ_ID)
);

CREATE TABLE JSON_DATA (
  SCAN_ID INT,

)
